provider "aws" {
  region = var.region

  default_tags {
    tags = {
      project     = var.project
      environment = "bootstrap"
      component   = "state-backend"
      managed_by  = "terraform"
    }
  }
}

data "aws_caller_identity" "current" {}

# ---------------------------------------------------------------------------
# Remote state bucket, shared by every environment root. Each environment
# writes to its own key prefix (envs/<env>/terraform.tfstate) inside this one
# bucket, so we only ever bootstrap one bucket, not one per environment.
#
# Locking: S3 native locking (`use_lockfile = true` on the S3 backend block in
# each env root) instead of a DynamoDB lock table — see docs/decisions.md.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "state" {
  bucket = "intake-tfstate-${data.aws_caller_identity.current.account_id}"

  # This bucket only ever holds Terraform state, which is regenerated by
  # `terraform apply`, so force_destroy is safe and keeps `make destroy`
  # (of the bootstrap root) genuinely clean.
  force_destroy = true

  tags = {
    Name = "intake-tfstate-bootstrap"
  }
}

resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id
  versioning_configuration {
    status = "Enabled"
  }
}

# SSE-S3 (AES256), not the project KMS key: the project key is created by the
# main stack, which itself depends on this bucket existing first. Using a
# customer-managed key here would recreate the same "backend can't depend on
# what it stores" bootstrapping problem one level down. State files are not
# one of the four data buckets the assignment grades on KMS granularity for.
resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "state" {
  bucket                  = aws_s3_bucket.state.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# ---------------------------------------------------------------------------
# GitHub Actions OIDC provider. This is an account-level, singleton resource
# (there is exactly one per AWS account regardless of how many environments
# or repos use it), so it is bootstrapped once here rather than duplicated in
# each environment stack. Per-environment CI deploy roles (created in
# infra/modules/stack) trust this provider by its deterministic ARN
# (arn:aws:iam::<account_id>:oidc-provider/token.actions.githubusercontent.com)
# without needing a cross-root remote-state read.
# ---------------------------------------------------------------------------
resource "aws_iam_openid_connect_provider" "github_actions" {
  url            = "https://token.actions.githubusercontent.com"
  client_id_list = ["sts.amazonaws.com"]
  thumbprint_list = [
    "6938fd4d98bab03faadb97b34396831e3780aea1",
    "1c58a3a8518e8759bf075b76b750d4f2df264fcd",
  ]

  tags = {
    Name = "intake-github-oidc"
  }
}
