provider "aws" {
  region = var.region

  default_tags {
    tags = {
      project     = var.project
      environment = "bootstrap"
      component   = "state-backend"
      managed_by  = "terraform"
    }
  }
}

data "aws_caller_identity" "current" {}

locals {
  # The single definition of the state bucket name. It is deterministic from
  # (project, account) by design: the environment roots and the ci-deploy IAM
  # policy have to name this bucket without being able to read this root's
  # state, so the name has to be derivable rather than looked up. Both derive
  # it with this same expression — keep them in step.
  state_bucket_name = "${var.project}-tfstate-${data.aws_caller_identity.current.account_id}"
}

# ---------------------------------------------------------------------------
# Remote state bucket, shared by every environment root. Each environment
# writes to its own key prefix (envs/<env>/terraform.tfstate) inside this one
# bucket, so we only ever bootstrap one bucket, not one per environment.
#
# Locking: S3 native locking (`use_lockfile = true` on the S3 backend block in
# each env root) instead of a DynamoDB lock table — see docs/decisions.md.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "state" {
  bucket = local.state_bucket_name

  # This bucket only ever holds Terraform state, which is regenerated by
  # `terraform apply`, so force_destroy is safe and keeps `make destroy`
  # (of the bootstrap root) genuinely clean.
  force_destroy = true

  tags = {
    Name = "${var.project}-tfstate-bootstrap"
  }
}

resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id
  versioning_configuration {
    status = "Enabled"
  }
}

# SSE-S3 (AES256), not the project KMS key: the project key is created by the
# main stack, which itself depends on this bucket existing first. Using a
# customer-managed key here would recreate the same "backend can't depend on
# what it stores" bootstrapping problem one level down. State files are not
# one of the four data buckets the assignment grades on KMS granularity for.
resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "state" {
  bucket                  = aws_s3_bucket.state.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Versioning above is the rollback path for a corrupted state file, so old
# versions are worth keeping — but not forever, or every apply accumulates one
# more permanently. 90 days is deliberately longer than the 30-day default the
# s3_bucket module uses for the data buckets: recovering a state file weeks
# after a bad apply is a real scenario, recovering a raw upload is not.
resource "aws_s3_bucket_lifecycle_configuration" "state" {
  depends_on = [aws_s3_bucket_versioning.state]

  bucket = aws_s3_bucket.state.id

  rule {
    id     = "expire-old-state-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 90
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

# Reject any non-TLS request to the state bucket. Cheap, and state files are
# the highest-value object in the account.
resource "aws_s3_bucket_policy" "state_tls_only" {
  bucket = aws_s3_bucket.state.id
  policy = data.aws_iam_policy_document.state_tls_only.json
}

data "aws_iam_policy_document" "state_tls_only" {
  statement {
    sid    = "DenyInsecureTransport"
    effect = "Deny"
    principals {
      type        = "AWS"
      identifiers = ["*"]
    }
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.state.arn,
      "${aws_s3_bucket.state.arn}/*",
    ]
    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

# ---------------------------------------------------------------------------
# GitHub Actions OIDC provider. This is an account-level SINGLETON — exactly
# one per AWS account for a given issuer URL, regardless of how many
# environments or repos use it — so it is bootstrapped once here rather than
# duplicated in each environment stack.
#
# Because it is a singleton, an account that already federates GitHub Actions
# for anything else already has it, and creating it again fails with
# EntityAlreadyExists. That would break the "no manual step beyond
# credentials" promise for a reviewer running this in their own sandbox, so it
# is behind a toggle: set `create_github_oidc_provider = false` and the
# environment roots will simply look up the existing one.
# ---------------------------------------------------------------------------
resource "aws_iam_openid_connect_provider" "github_actions" {
  count = var.create_github_oidc_provider ? 1 : 0

  url            = "https://token.actions.githubusercontent.com"
  client_id_list = ["sts.amazonaws.com"]

  # AWS no longer validates these for the GitHub issuer — it trusts the
  # certificate chain directly — but the argument is still required by the API,
  # and these are GitHub's two published values. They are not a security
  # control here; the `sub`/`aud` conditions on the role are.
  thumbprint_list = [
    "6938fd4d98bab03faadb97b34396831e3780aea1",
    "1c58a3a8518e8759bf075b76b750d4f2df264fcd",
  ]

  tags = {
    Name = "${var.project}-github-oidc"
  }
}
